# -*- coding: utf-8 -*-
"""Blink.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oG5enE-7QJghi8eEWdaeGtZKSy08Kryv
"""

import cv2
import mediapipe as mp
from scipy.spatial import distance

mp_face_mesh = mp.solutions.face_mesh

face_mesh = mp_face_mesh.FaceMesh(
    max_num_faces=1,
    refine_landmarks=True
)

cap = cv2.VideoCapture(0)

blink_count = 0
blink_detected = False

LEFT_EYE = [33,160,158,133,153,144]

def EAR(eye_points):

    vertical1 = distance.euclidean(
        eye_points[1],
        eye_points[5]
    )

    vertical2 = distance.euclidean(
        eye_points[2],
        eye_points[4]
    )

    horizontal = distance.euclidean(
        eye_points[0],
        eye_points[3]
    )

    ear = (vertical1 + vertical2)/(2*horizontal)

    return ear


while True:

    success, frame = cap.read()

    if not success:
        break

    frame = cv2.flip(frame,1)

    h,w,_ = frame.shape

    rgb = cv2.cvtColor(
        frame,
        cv2.COLOR_BGR2RGB
    )

    results = face_mesh.process(rgb)

    if results.multi_face_landmarks:

        for face_landmarks in results.multi_face_landmarks:

            eye_coordinates=[]

            for idx in LEFT_EYE:

                landmark = face_landmarks.landmark[idx]

                x = int(landmark.x*w)
                y = int(landmark.y*h)

                eye_coordinates.append((x,y))

                cv2.circle(
                    frame,
                    (x,y),
                    2,
                    (0,255,0),
                    -1
                )

            ear = EAR(eye_coordinates)

            cv2.putText(
                frame,
                f"EAR:{round(ear,2)}",
                (30,50),
                cv2.FONT_HERSHEY_SIMPLEX,
                1,
                (0,255,0),
                2
            )

            if ear < 0.20:

                if not blink_detected:

                    blink_count +=1
                    blink_detected=True

            else:

                blink_detected=False


            cv2.putText(
                frame,
                f"Blinks:{blink_count}",
                (30,100),
                cv2.FONT_HERSHEY_SIMPLEX,
                1,
                (0,0,255),
                2
            )


    cv2.imshow(
        "Blink Detection",
        frame
    )

    if cv2.waitKey(1) & 0xFF==ord('q'):
        break

cap.release()
cv2.destroyAllWindows()